### ISSUE TITLE
uninstallable with yarn 1.6.0 and 1.9.4 on MacOS

### ISSUE THREAD

**Issue by simevo** [coreui/coreui#22]
`yarn add @coreui/coreui` reports:
```
yarn add v1.6.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@coreui/coreui > bootstrap@4.1.3" has unmet peer dependency "jquery@1.9.1 - 3".
warning "@coreui/coreui > bootstrap@4.1.3" has unmet peer dependency "popper.js@^1.14.3".
warning " > @coreui/coreui@2.0.4" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > @coreui/coreui@2.0.4" has unmet peer dependency "perfect-scrollbar@^1.3.0".
warning " > @coreui/coreui@2.0.4" has unmet peer dependency "popper.js@^1.14.3".
[4/4] 📃  Building fresh packages...
[1/1] ⠄ @coreui/coreui
[-/1] ⠄ waiting...
error /Library/WebServer/Documents/booh/node_modules/@coreui/coreui: Command failed.
Exit code: 1
Command: coreui-plugin-npm-postinstall
Arguments: 
Directory: /Library/WebServer/Documents/booh/node_modules/@coreui/coreui
Output:
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Library/WebServer/Documents/booh/node_modules/@coreui/coreui-plugin-npm-postinstall/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```
this can be fixed running this command before:
```
yarn add chalk
```

**Comment by Preen** [comment]
Have the same problem but with `npm -i`. Also fixed by adding chalk to devDependencies.
