### ISSUE TITLE
coreui-plugin-npm-postinstall dependency missing

### ISSUE THREAD

**Issue by hamishgraham** [coreui/coreui#25]
I'm trying to include CoreUI using Gradle and WebJars:
```compile 'org.webjars.npm:coreui__coreui:2.0.4'```

 I get the following error:

```
Could not find any matches for org.webjars.npm:coreui__coreui-plugin-npm-postinstall:[1.0.2,2) as no versions of org.webjars.npm:coreui__coreui-plugin-npm-postinstall are available.
  Required by:
      project : > org.webjars.npm:coreui__coreui:2.0.4
```

I tried to add the dependency via the[ Webjars website](https://www.webjars.org/) but it did not work as the Github project is missing:
https://github.com/coreui/coreui-plugin-npm-postinstall

**Comment by hamishgraham** [comment]
Further to this... I also tried to use NPM and it also failed due to the `coreui-plugin-npm-postinstall` dependency.

```npm install @coreui/coreui --save```

Errors from log:
```
145 verbose stack Error: @coreui/coreui@2.0.4 postinstall: `coreui-plugin-npm-postinstall`
145 verbose stack Exit status 1
145 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
145 verbose stack     at EventEmitter.emit (events.js:182:13)
145 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
145 verbose stack     at ChildProcess.emit (events.js:182:13)
145 verbose stack     at maybeClose (internal/child_process.js:961:16)
145 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
146 verbose pkgid @coreui/coreui@2.0.4
147 verbose cwd /tmp/
148 verbose Darwin 17.4.0
149 verbose argv "/usr/local/Cellar/node/10.6.0/bin/node" "/usr/local/bin/npm" "install" "@coreui/coreui" "--save"
150 verbose node v10.6.0
151 verbose npm  v6.4.0
152 error code ELIFECYCLE
153 error errno 1
154 error @coreui/coreui@2.0.4 postinstall: `coreui-plugin-npm-postinstall`
154 error Exit status 1
155 error Failed at the @coreui/coreui@2.0.4 postinstall script.
155 error This is probably not a problem with npm. There is likely additional logging output above.
156 verbose exit [ 1, true ]
```

**Comment by hamishgraham** [comment]
I tried the latest v2.1.4 and the same issue persists.

**Comment by huuquyasb** [comment]
the same issue v2.15. Please fix..

**Comment by bessone** [comment]
same to me with v2.15

**Comment by xidedix** [comment]
everyone facing this issue: 
- remove `package-lock.json` 
- update `@coreui/coreui` to `2.1.6`
- run `npm install`  
- please let us know is it any better
